### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by ariselseng** [dgoring/DomQuery#1]
Is there any plans to support 8.1?

**Comment by dgoring** [comment]
@ariselseng the [constraint](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) is for `^8.0.0` which includes all PHP versions upto but not including PHP `9.0`

So it should work fine with PHP 8.1

unless there is a specific error you are having, in which case please provide the details of the error

**Comment by ariselseng** [comment]
https://github.com/Rct567/DomQuery/compare/master...raspberryswwwirl:DomQuery:master

There is issues with return types in php 8.1

**Comment by dgoring** [comment]
@ariselseng Please can you provide the exact issue and steps to reproduce
